// frontend/src/App.tsx
import { useState } from "react";
import { InputPane } from "./components/InputPane";
import { ResultPane } from "./components/ResultPane";
import HeatMap from "./components/HeatMap";
import { getScore, ScoreResponse } from "./utils/api";

function App() {
  const [jobDesc, setJobDesc] = useState<string>("");
    const [resume, setResume] = useState<string>("");
      const [result, setResult] = useState<ScoreResponse | null>(null);
        const [loading, setLoading] = useState<boolean>(false);
          const [error, setError] = useState<string>("");

            const calculate = async () => {
                setLoading(true);
                    setError("");
                        try {
                              const data = await getScore(jobDesc, resume);
                                    setResult(data);
                                        } catch (e) {
                                              setError("⚠️ Failed to contact the backend. Please try again.");
                                                  } finally {
                                                        setLoading(false);
                                                            }
                                                              };

                                                                return (
                                                                    <div className="min-h-screen bg-gradient-to-br from-purple-950 via-purple-900 to-purple-950 text-gray-100 flex flex-col items-center p-6">
                                                                          {/* Header */}
                                                                                <header className="text-center mb-8">
                                                                                        <h1 className="text-4xl font-extrabold tracking-wide bg-gradient-to-r from-pink-400 to-blue-400 text-transparent bg-clip-text drop-shadow-lg">
                                                                                                  Resume Scorecard
                                                                                                          </h1>
                                                                                                                  <p className="mt-2 text-gray-300 max-w-xl mx-auto">
                                                                                                                            Paste a job description and your résumé below. Our AI will analyze
                                                                                                                                      keyword matches and give you a compatibility score.
                                                                                                                                              </p>
                                                                                                                                                    </header>

                                                                                                                                                          {/* Input Panels */}
                                                                                                                                                                <div className="grid md:grid-cols-2 gap-6 w-full max-w-5xl">
                                                                                                                                                                        <InputPane
                                                                                                                                                                                  label="Job Description"
                                                                                                                                                                                            value={jobDesc}
                                                                                                                                                                                                      onChange={setJobDesc}
                                                                                                                                                                                                              />
                                                                                                                                                                                                                      <InputPane label="Your Résumé" value={resume} onChange={setResume} />
                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                  {/* Action Button */}
                                                                                                                                                                                                                                        <div className="my-6 flex justify-center">
                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                          onClick={calculate}
                                                                                                                                                                                                                                                                    disabled={loading || !jobDesc || !resume}
                                                                                                                                                                                                                                                                              className={`px-8 py-3 rounded-xl font-semibold shadow-md transition-transform transform ${
                                                                                                                                                                                                                                                                                          loading || !jobDesc || !resume
                                                                                                                                                                                                                                                                                                        ? "bg-gray-600 cursor-not-allowed"
                                                                                                                                                                                                                                                                                                                      : "bg-gradient-to-r from-blue-600 to-purple-600 hover:scale-105 hover:from-blue-500 hover:to-purple-500"
                                                                                                                                                                                                                                                                                                                                } text-white`}
                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                  {loading ? "⏳ Analyzing…" : "🚀 Calculate Score"}
                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                      {/* Error Message */}
                                                                                                                                                                                                                                                                                                                                                                            {error && (
                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-red-400 text-center font-medium mt-2">{error}</p>
                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                {/* Results */}
                                                                                                                                                                                                                                                                                                                                                                                                      {result && (
                                                                                                                                                                                                                                                                                                                                                                                                              <div className="w-full max-w-5xl mt-8 space-y-6">
                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Score Display */}
                                                                                                                                                                                                                                                                                                                                                                                                                                  <ResultPane percent={result.percent}>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-gray-300 mt-2 text-sm text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            The score reflects how well your résumé matches the job
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          description keywords.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </ResultPane>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Heatmaps Inline */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="grid md:grid-cols-2 gap-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="bg-purple-950/40 rounded-xl p-4 shadow-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-lg font-semibold text-pink-300 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Job Description Heatmap
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <HeatMap words={result.jobDescHeatmap} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="bg-purple-950/40 rounded-xl p-4 shadow-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-lg font-semibold text-blue-300 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Résumé Heatmap
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <HeatMap words={result.resumeHeatmap} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default App;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      